"""
Mapping of lower case versions of raw site parsed strings of team names to
their corresponding team ID.
"""

team_mappings = {
    "adelaide": "Adelaide",
    "crows": "Adelaide",
    "adelaide crows": "Adelaide",
    "brisbane": "Brisbane Lions",
    "brisbane lions": "Brisbane Lions",
    "lions": "Brisbane Lions",
    "carlton": "Carlton",
    "carlton blues": "Carlton",
    "blues": "Carlton",
    "essendon": "Essendon",
    "essendon bombers": "Essendon",
    "bombers": "Essendon",
    "collingwood": "Collingwood",
    "collingwood magpies": "Collingwood",
    "magpies": "Collingwood",
    "fremantle": "Fremantle",
    "fremantle dockers": "Fremantle",
    "dockers": "Fremantle",
    "geelong cats": "Geelong",
    "geelong": "Geelong",
    "cats": "Geelong",
    "gold coast suns": "Gold Coast",
    "gold coast": "Gold Coast",
    "suns": "Gold Coast",
    "greater western sydney giants": "Greater Western Sydney",
    "greater western sydney": "Greater Western Sydney",
    "giants": "Greater Western Sydney",
    "gws giants": "Greater Western Sydney",
    "gws": "Greater Western Sydney",
    "hawthorn": "Hawthorn",
    "hawks": "Hawthorn",
    "hawthorn hawks": "Hawthorn",
    "melbourne demons": "Melbourne",
    "melbourne": "Melbourne",
    "demons": "Melbourne",
    "north melbourne kangaroos": "North Melbourne",
    "north melbourne": "North Melbourne",
    "kangaroos": "North Melbourne",
    "port adelaide power": "Port Adelaide",
    "port adelaide": "Port Adelaide",
    "power": "Port Adelaide",
    "richmond tigers": "Richmond",
    "richmond": "Richmond",
    "tigers": "Richmond",
    "st kilda saints": "St Kilda",
    "st kilda": "St Kilda",
    "saints": "St Kilda",
    "sydney swans": "Sydney",
    "sydney": "Sydney",
    "swans": "Sydney",
    "west coast eagles": "West Coast",
    "west coast": "West Coast",
    "eagles": "West Coast",
    "western bulldogs": "Western Bulldogs",
    "bulldogs": "Western Bulldogs",
}
